### PR TITLE
Finish the project

### PR DESCRIPTION
**Pull request by srueda27**
Page cloning with bootstrap framework
Mix layout between bootstrap and CSS Grid

### CODE REVIEW

**Comment by Anna-Myzukina** [comment]
### Pull Request under the review by Anna Muzykina (TSE)

**Comment by Anna-Myzukina** [comment]
### Hi Santiago!
### Nice job! Project looks! :+1: The readme file is very descriptive!

### But your project still needs changes.

Kindly recommended checking HTML markup with this validator https://validator.w3.org/#validate_by_upload.
screen


err

### Page structure
#### Navigation bar:
*  It should contain current date
date


* Use Bootstrap CSS classes everywhere for styling (for example Grid layout and Flex)
screen

* Please remember that feature branch should be with descriptive name
img

img

### Make changes and submit another code review request.

*If you have any questions, let me know on slack (@Anna-Muzykina) and I will be glad to clarify with you.*

*Happy coding 😄*

**Review by Anna-Myzukina — CHANGES_REQUESTED** [review]
The project needs changes

**Comment by srueda27** [comment]
@Anna about the descriptive branch, I used different branches on my local environment as you can see
image
but since I just get to create one pull request for the entire project I like to call it "Development"

**Comment by izaiasneto4** [comment]
#### Hi @srueda27! Nice job doing the requested changes :muscle: 
#### Project approved. :+1: 

TSE: Izaias Neto

**Pull request merged**
